# Scala CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    docker:
      - image: flurdy/activator-mini:1.3.12-alpine

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
          - v7.4-dependencies-{{ checksum "build.sbt" }}--{{ checksum ".circleci/config.yml" }}
          - v7.4-dependencies-

      - run:
          name: Compile
          command: cat /dev/null | activator test:compile

      - run:
          name: Test build
          command: cat /dev/null | activator test:test

      - run:
          name: Package application
          command: cat /dev/null | activator stage

      - save_cache:
          paths:
            - ~/.m2
            - ~/.ivy2
            - ~/.sbt
            # - ~/.docker
          key: v7.4-dependencies--{{ checksum "build.sbt" }}--{{ checksum ".circleci/config.yml" }}

      - store_artifacts:
          path: target/universal/stage

      # - run:
      #     name: Install Docker client
      #     command: |
      #        apk update
      #        apk add docker
      #
      # - setup_remote_docker:
      #     docker_layer_caching: true
      #
      # - run:
      #     name: Build Docker image
      #     command: docker build -t $DOCKER_BUILD_TAG:latest .
      #
      # - run:
      #     name: Tag Docker image
      #     command: docker tag $DOCKER_BUILD_TAG:latest $DOCKER_TAG
      #
      # - run:
      #     name: Login to Docker registry
      #     command: docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY
      #
      # - run:
      #     name: Push image to registry
      #     command: docker push $DOCKER_TAG

      - run:
          name: Deploy to Heroku staging
          command: cat /dev/null | activator -DherokuApp=$HEROKU_APP deployHeroku
