# Scala CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    docker:
      - image: flurdy/activator-mini:1.3.12-alpine

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
          - v7.4-dependencies-{{ checksum "build.sbt" }}--{{ checksum ".circleci/config.yml" }}
          - v7.4-dependencies-

      - run:
          name: Compile
          command: cat /dev/null | activator test:compile

      - run: 
          name: Install Chrome Driver
          command: |
             apk update
             apk add chromium-chromedriver

      - run:
          name: Test build
          command: cat /dev/null | activator test:test

      - run:
          name: Package application
          command: cat /dev/null | activator stage

      - save_cache:
          paths:
            - ~/.m2
            - ~/.ivy2
            - ~/.sbt
            # - ~/.docker
          key: v7.4-dependencies--{{ checksum "build.sbt" }}--{{ checksum ".circleci/config.yml" }}

      - store_artifacts:
          path: target/universal/stage

      - run:
          name: Deploy to Heroku staging
          command: cat /dev/null | activator -DherokuApp=$HEROKU_APP deployHeroku
